### ISSUE TITLE
Permissions issue in Android 6.0

### ISSUE THREAD

**Issue by mrezutko** [chen-fishbein/codenameone-calendar#2]
In android 6.0 there is never a prompt for read and write access to the calendar, thus it crashes with a security exception.  In previous versions it prompts as expected at first run and runs fine.  Also in 6.0 hasPermissions() returns true even if it doesn't have permissions.

**Comment by jegesh** [comment]
+1

**Comment by codenameone** [comment]
Fixed by recent pull request
